### ISSUE TITLE
How to inject the chaincode id to external chaincode service?

### ISSUE THREAD

**Issue by bh4rtp** [TommyStarK/hyperledger-fabric-kubernetes#3]
Currently the chaincode id is hard coded as `chaincode-as-external-service:33b295bb4ac3f8dead7bddb9e86315aa7b3729b76d6d53f9379ddba6db900f7f`. Should it be injected into chaincode deployments yaml from the `package id` returned by `peer lifecycle install` before created? Thanks!

**Comment by TommyStarK** [comment]
Hi @bh4rtp,

Yes absolutely, now the chaincode package ID is hardcoded. This is due to the fact that the chaincode package has already been generated and is present within the `chaincode-as-external-service` folder. Therefore, the package ID computed by the peers will always be the same for a given peer version.

If you wish to dynamically generate the  chaincode package then you must inject the resulting package ID into the chaincode deployment, you are absolutely right.
This is due to the fact that when creating the `tar` archive there are some metadata embedded and thus, the pacakage ID will always be different (as the creation date of the tar archive is never the same).

Indeed you can retrieve the package ID from either the `peer lifecycle installed` or `peer lifecyle queryInstalled` commands.

One possible solution could be, once you generated the chaincode package to store the package ID and reuse it if you need to install/approve the chaincode multiple times.
You could use a persistent volume, bump the package id into a file for example and read the content of this file wherever you need to install the chaincode.
From the chaincode point of view, you could mount this volume into the chaincode pod, read the package ID from the file and export it to make it available before starting the chaincode server.

I hope it answers your question.
Best,

**Comment by bh4rtp** [comment]
Thanks. I get know why your chaincode id is hardcoded and the chaincode id varies because of the tarball create time. I am implementing the injection of chaincode id into the external chaincode pod.BTW, this is a good example for external chaincode builder.Allen------------------ Original ------------------From: Thomas Milox  ***@***.***>Date: Mon,Mar 15,2021 2:20 AMTo: TommyStarK/hyperledger-fabric-kubernetes ***@***.***>Cc: bh4rtp ***@***.***>, Mention ***@***.***>Subject: Re: [TommyStarK/hyperledger-fabric-kubernetes] How to inject thechaincode id to external chaincode service? (#3)
Hi @bh4rtp,
Yes absolutely, now the chaincode package ID is hardcoded. This is due to the fact that the chaincode package has already been generated and is present within the chaincode-as-external-service folder. Therefore, the package ID computed by the peers will always be the same for a given peer version.
If you wish to dynamically generate the  chaincode package then you must inject the resulting package ID into the chaincode deployment, you are absolutely right.
This is due to the fact that when creating the tar archive there are some metadata embedded and thus, the pacakage ID will always be different (as the creation date of the tar archive is never the same).
Indeed you can retrieve the package ID from either the peer lifecycle installed or peer lifecyle queryInstalled commands.
One possible solution could be, once you generated the chaincode package to store the package ID and reuse it if you need to install/approve the chaincode multiple times.
You could use a persistent volume, bump the package id into a file for example and read the content of this file wherever you need to install the chaincode.
From the chaincode point of view, you could mount this volume into the chaincode pod, read the package ID from the file and export it to make it available before starting the chaincode server.
I hope it answers your question.
Best,

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/TommyStarK/hyperledger-fabric-kubernetes/issues/3#issuecomment-798954187",
"url": "https://github.com/TommyStarK/hyperledger-fabric-kubernetes/issues/3#issuecomment-798954187",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by TommyStarK** [comment]
Thank you very much, it matters to me. In fact 
I've already implemented dynamic injection of the chaincode package id to avoid any hardcoded value but this is for an IBM project and unfortunately I cannot disclose the code.
However, feel free to ask me any question I'll be glad to help.

Best,
